{% set tpl = ix_lib.base.render.Render(values) %}

{% set c1 = tpl.add_container(values.consts.urbackup_container_name, "image") %}

{% do c1.set_user(0,0) %}
{% do c1.add_caps(["CHOWN", "FOWNER", "DAC_OVERRIDE", "SETUID", "SETGID"]) %}
{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set perms_config = {"uid": 0, "gid": 0, "mode": "check"} %}

{% do c1.healthcheck.set_test("http", {"port": values.network.web_port.port_number}) %}

{% do c1.environment.add_user_envs(values.urbackup.additional_envs) %}

{% do c1.add_storage(values.consts.backup_path, values.storage.backups) %}
{% do perm_container.add_or_skip_action("backups", values.storage.backups, perms_config) %}

{% do c1.add_storage(values.consts.database_path, values.storage.database) %}
{% do perm_container.add_or_skip_action("database", values.storage.database, perms_config) %}

{% do c1.add_storage(values.consts.www_path, values.storage.wwwfolder) %}
{% do perm_container.add_or_skip_action("www-folder", values.storage.wwwfolder, perms_config) %}

{% for store in values.storage.additional_storage %}
  {% do c1.add_storage(store.mount_path, store) %}
  {% do perm_container.add_or_skip_action(store.mount_path, store, perms_config) %}
{% endfor %}

{% do c1.add_port(values.network.web_port, {"container_port": values.consts.internal_webui_port}) %}
{% do c1.add_port(values.network.backup_port_1, {"container_port": values.consts.internal_backup_port_1}) %}
{% do c1.add_port(values.network.backup_port_2, {"container_port": values.consts.internal_backup_port_2}) %}
{% do c1.add_port(values.network.backup_port_3, {"container_port": values.consts.internal_backup_port_3, "protocol": "udp"}) %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do c1.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% do tpl.portals.add_portal({"port": values.network.web_port.port_number}) %}

{{ tpl.render() | tojson }}
