app_version: 2.5.x
capabilities:
- description: urbackup is able to change file ownership.
  name: CHOWN
- description: urbackup is able to set the setuid attribute on a file.
  name: SETUID
- description: urbackup is able to set the setgid attribute on a file.
  name: SETGID
categories:
- backup
description: UrBackup is an easy to setup Open Source client/server backup system,
  that through a combination of image and file backups accomplishes both data safety
  and a fast restoration time.
home: https://github.com/uroni/urbackup_backend
host_mounts: []
icon: https://media.sys.truenas.net/apps/urbackup/icons/icon.png
keywords:
- backup
lib_version: 2.1.11
lib_version_hash: ccf6e3fd289c920ef530a4280b8ea13f8488e63928f68e2bbaf6e3dea917c81e
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: urbackup
run_as_context:
- description: urbackup runs as the root user.
  gid: 0
  group_name: urbackup
  uid: 0
  user_name: urbackup
screenshots: []
sources:
- https://github.com/uroni/urbackup_backend
title: urbackup
train: community
version: 2.1.11
