images:
  image:
    repository: uroni/urbackup-server
    tag: 2.5.x

consts:
  urbackup_container_name: urbackup-server
  internal_webui_port: 55414
  internal_backup_port_1: 55413
  internal_backup_port_2: 55415
