images:
  image:
    repository: uroni/urbackup-server
    tag: 2.5.x

consts:
  urbackup_container_name: urbackup-server
  perms_container_name: permissions
  internal_webui_port: 55414
  internal_backup_port_1: 55413
  internal_backup_port_2: 55415
  backup_path: /backups
  database_path: /var/urbackup
  www_path: /usr/share/urbackup
